footer
Diadchenko/IceCreamTeam pull request #5
Opened 2022-06-10 13:46 UTC by Olga82K

поки що верхні падінги проставлені умовно

2022-06-10 19:48 UTC, yuriipanasiuk requested changes

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +    @media screen and (min-width: 1200px) {
змінити (min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
(min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +    @media screen and (min-width: 1200px) {
змінити (min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
змінити (min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
змінити (min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  :focus {
:focus замінити на &:focus

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
замінити (min-width: 1200px) на 1280px

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  font-style: normal;
font style: normal and font weight: 400 є по замовчуванню, не потрібно прописувати зайвий раз стилі, які браузер встановлює самостійно. Тому будь-ласка передивись увесь код і зайві стилі забери :)

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  font-family: 'DM Sans';
font-family: 'DM Sans'; встановлено на body

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  font-size: 14px;
зайвий код, font-size: 14px браузер встановлює по замовчуванню, варто прописувати, якщо це заговок

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/sass/layers/_footer.scss
> +  margin-right: 28.24px;
використовуй лише ціла числа, без десятих та сотих

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="20" height="20">
розміри іконок соціальний мерез 34х34, ти дивишся на розмір вектора, який на різку іконку різний.
![image](https://user-images.githubusercontent.com/97585294/173136030-b37454ac-c9b1-4350-a482-f11fdda1aa62.png)

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="20.4" height="15.87">
не вірно вказаний розмір

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="9.35" height="20.4">
не вірно вказаний розмір

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/partials/footer.html
> +            <a class="link footer-tel__number" href="tel:+">
можна вказати href="tel:+61(0)383766284"  щоб працював мобільний виклик

2022-06-10 19:48 UTC, yuriipanasiuk commented on src/partials/footer.html
> +        © 2019 - IceCream. All Rights Reserved.
знак копірайт не можна вставляти просто копіюванням, оскільки буде по різному відображатись у користувачів. Потрібно використовувати код в стилі &#169
https://www.toptal.com/designers/htmlarrows/symbols/

2022-06-10 20:07 UTC, Olga82K commented on src/sass/layers/_footer.scss
> +    @media screen and (min-width: 1200px) {
виправила

2022-06-10 20:07 UTC, Olga82K commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
виправила

2022-06-10 20:08 UTC, Olga82K commented on src/sass/layers/_footer.scss
> +    @media screen and (min-width: 1200px) {
виправила

2022-06-10 20:08 UTC, Olga82K commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
виправила

2022-06-10 20:08 UTC, Olga82K commented on src/sass/layers/_footer.scss
> +  @media screen and (min-width: 1200px) {
виправила

2022-06-10 20:13 UTC, Olga82K commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="20" height="20">
Я тут пішла тим шляхом, що й в домашці. Розмір 34 на 34 завісила на клас самого посилання, і через  border-radius: 50%; надала йому округлу форму. На мій погляд те й вийшло, але треба буде щоб ще хтось глянув як воно в браузері після компіляції виглядатиме

2022-06-10 20:13 UTC, Olga82K commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="20.4" height="15.87">
пояснення вище

2022-06-10 20:13 UTC, Olga82K commented on src/partials/footer.html
> +                <svg class="footer-soc-icon" width="9.35" height="20.4">
пояснення вище

2022-06-10 20:15 UTC, Olga82K commented on src/partials/footer.html
> +            <a class="link footer-tel__number" href="tel:+">
ммм, робила аналогічно з домашкою, а зараз він не працює? як це можна перевірити?

2022-06-10 20:25 UTC, Olga82K commented on src/partials/footer.html
> +        © 2019 - IceCream. All Rights Reserved.
дякую, не знала, виправлю

2022-06-11 15:32 UTC, yuriipanasiuk commented on src/partials/footer.html
> +            <a class="link footer-tel__number" href="tel:+">
в href просто добавляється код для того щоб, коли користувач натискає на номер побільного телефону йде набір номера, це також використовується для мила

2022-06-11 15:45 UTC, yuriipanasiuk approved these changes

2022-06-11 17:30 UTC, Diadchenko approved these changes

2022-06-11 18:50 UTC, merged